name: tm_developer_site
description: Flutter and Firebase developer landing page.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  web: ^1.1.1
  firebase_core: ^4.11.0
  firebase_core_web: ^3.9.0
  cloud_firestore: ^6.6.0
  cloud_firestore_web: ^5.6.0
  firebase_app_check: ^0.4.5
  firebase_app_check_web: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/apps/coffee_timer/
    - assets/apps/volume_changer/
    - assets/apps/recipe_archive/
